#!bash

# restic environment variables
#
# see `man restic` for details
#
#RESTIC_PASSWORD_FILE=/etc/rheostoick.d/password
#RESTIC_PASSWORD_COMMAND="gpg --quiet --decrypt /etc/rheostoick.d/password.gpg" 
#RESTIC_REPOSITORY=/backup/restic
#RESTIC_REPOSITORY_FILE=/etc/rheostoick.d/repo

# file with paths/patterns to exclude from the backup
#
# used in --exclude-file option for `restic backup`
#
#RHEOSTOICK_EXCLUDE_FILE=/etc/rheostoick.d/exclude

# log file
#
# use a path to log to a file, '-' to log to stdout,
# or 'syslog' to log to syslog (requires logger)
#
#RHEOSTOICK_LOG_FILE=-

# is the repository supposed to be mounted?
#
# use '1' to check that the repository is a mount point, '0' otherwise
#
#RHEOSTOICK_MOUNTED=1

# arguments to pass to `restic forget` when pruning
#RHEOSTOICK_PRUNE_ARGS="--prune --keep-hourly 12 --keep-daily 7 --keep-weekly 4 --keep-monthly 3"

# hook options
#
# check_integ: spool file where checkmk integrity check results should be written to
#
#CHECKMK_INTEGRITY_SPOOL=/var/lib/check_mk_agent/spool/$((8*24*60*60))_check_restic_integrity
#
# check_snaps: spool file where checkmk integrity check results should be written to
#
#CHECKMK_SNAPSHOTS_SPOOL=/var/lib/check_mk_agent/spool/$((3*24*60*60))_check_restic_snapshots
#
# check_snaps: thresholds formatted like period:warn:crit
#
#CHECKMK_SNAPSHOTS_THRESHOLDS=1day:10:6

