#!bash

# restic environment variables
# https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables
#RESTIC_PASSWORD_FILE=/etc/rheostoick.d/password
#RESTIC_PASSWORD_COMMAND="gpg --quiet --decrypt /etc/rheostoick.d/password.gpg" 
#RESTIC_REPOSITORY=/backup/restic
#RESTIC_REPOSITORY_FILE=/etc/rheostoick.d/repo

# if you define a variable like RHEOSTOICK_FOO=args,
# then `rheostoic foo` will run `restic args`
RHEOSTOICK_BACKUP="backup -v --exclude-file=/etc/rheostoick.d/exclude /"
RHEOSTOICK_PRUNE="forget --prune --keep-hourly 12 --keep-daily 7 --keep-weekly 4 --keep-monthly 3"

# log file
#
# use a path to log to a file, '-' to log to stdout,
# or 'syslog' to log to syslog (requires logger)
#
#LOG_FILE=-

# is the repository supposed to be mounted?
#
# use '1' to check that the repository is a mount point, '0' otherwise
#
#RHEOSTOICK_MOUNTED=1

# arguments to pass to `restic forget` when pruning

# hook options
#
# check_integ: spool file where checkmk integrity check results should be written to
#
#CHECKMK_INTEGRITY_SPOOL=/var/lib/check_mk_agent/spool/$((8*24*60*60))_check_restic_integrity
#
# check_snaps: spool file where checkmk integrity check results should be written to
#
#CHECKMK_SNAPSHOTS_SPOOL=/var/lib/check_mk_agent/spool/$((3*24*60*60))_check_restic_snapshots
#
# check_snaps: thresholds formatted like period:warn:crit
#
#CHECKMK_SNAPSHOTS_THRESHOLDS=1day:10:6

