#!bash

# all variables are exported to the environment,
# so you can define restic environment variables here
# https://restic.readthedocs.io/en/latest/040_backup.html#environment-variables
#RESTIC_PASSWORD_FILE=/etc/resticbackup.d/password
#RESTIC_PASSWORD_COMMAND="gpg --quiet --decrypt /etc/resticbackup.d/password.gpg" 
#RESTIC_REPOSITORY=/backup/restic
#RESTIC_REPOSITORY_FILE=/etc/resticbackup.d/repo

# if you define a variable like RESTICBACKUP_FOO=args,
# then `resticbackup foo` will run `restic args`
RESTICBACKUP_BACKUP="backup -v --exclude-file=/etc/resticbackup.d/exclude /"
RESTICBACKUP_PRUNE="forget --prune --keep-hourly 12 --keep-daily 7 --keep-weekly 4 --keep-monthly 3"

# logging: use a path to log to a file, '-' to log to stdout,
# or 'syslog' to log to syslog (requires logger)
#LOG_FILE=-

# hook settings
#
# check-integ: spool file where checkmk integrity check results should be written to
#
#CHECKMK_INTEGRITY_SPOOL=/var/lib/check_mk_agent/spool/$((8*24*60*60))_check_restic_integrity
#
# check-snaps: spool file where checkmk integrity check results should be written to
#
#CHECKMK_SNAPSHOTS_SPOOL=/var/lib/check_mk_agent/spool/$((3*24*60*60))_check_restic_snapshots
#
# check-snaps: thresholds formatted like period:warn:crit
#
#CHECKMK_SNAPSHOTS_THRESHOLDS=1day:6:10

